#!/usr/bin/env bash
# Installs nginx web server
sudo apt-get -y install nginx
sudo service nginx start
sudo touch /var/www/html/index.html
sudo chown -R $USER:$USER /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
