#!/usr/bin/env bash
# Install nginx
# Redirect a url
# Have a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

location="\n\tlocation /redirect_me {\n\trewrite ^/redirect_me(.*)$ https://www.grymoire.com/Unix/Sed.html permanent;\n\t}"
sudo sed "/server_name _;/ a\ $location" -i /etc/nginx/sites-enabled/default

error="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed "/server_name _;/a\ $error" -i /etc/nginx/sites-enabled/default

sudo service nginx restart
