#!/usr/bin/env bash
#install and configure HAproxy to setup lb-01 server as load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

frontend="\nfrontend localhost\n\tbind *:80\n\tmode http\n\tdefault_backend web-servers"
backend="\nbackend web-servers\n\tbalance roundrobin\n\tserver 36049-web-01 54.84.174.165:80 check\n\tserver 36049-web-02 52.5.217.40:80 check"

sed -i -e "\$a\ $frontend" /etc/haproxy/haproxy.cfg
sed -i -e "\$a\ $backend" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
