#!/usr/bin/env bash
# configures nginx to listen on port 80

rm /etc/nginx/sites-enabled/mysite.com
ln -s /etc/nginx/sites-available/mysite.com /etc/nginx/sites-enabled/mysite.com
service nginx restart
