#!/usr/bin/env bash
# displays the content of the file /etc/passwd
#+ and display only:
#	username
#	user id
#	Home directory path for the user

list=$(cat /etc/passwd)
while read -r var
do
	echo "$var" | cut -d ":" -f 1,3,6
done < <(echo "$list")
