#!/usr/bin/env bash
# displays the content of the file /etc/passwd
#+ and display only:
#	username
#	user id
#	Home directory path for the user

list="$(cat /etc/passwd)"
for i in $list
do
	echo "$i" | cut -d ":" -f 1,3,6
done
