#!/usr/bin/env bash
# executes whoami command under the user passed as an argument

#!/usr/bin/env bash
# Executes whoami command under the user passed as an argument
if [ "$1" ]; then
	sudo -u "$1" HOME= bash -c "whoami"
else
	whoami
fi
