#!/usr/bin/env bash

# Change permissions of nginx.conf
chmod 644 /etc/nginx/nginx.conf

# Modify nginx.conf to use nginx user
sed -i "s/# user www-data/user nginx/" /etc/nginx/nginx.conf

# Update default site to listen on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Stop Apache if running (assuming it uses the "apache2" service name)
pkill apache2

# Start Nginx as the nginx user
sudo -u nginx /bin/bash -c "service nginx start"
